bag/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.view_bag, name="view_bag"),
    path("add/<item_id>/", views.add_to_bag, name="add_to_bag"),
    path("adjust/<str:product_size_id>", views.adjust_bag, name="adjust_bag"),
    path(
        "remove/<str:product_size_id>",
        views.remove_from_bag,
        name="remove_from_bag",
    ),
]

checkout/urls.py
from django.urls import path

from . import views
from .webhooks import webhook

urlpatterns = [
    path("", views.checkout, name="checkout"),
    path(
        "checkout_success/<order_number>",
        views.checkout_success,
        name="checkout_success",
    ),
    path(
        "cache_checkout_data",
        views.cache_checkout_data,
        name="cache_checkout_data",
    ),
    path("wh", webhook, name="webhook"),
]

cyclebay/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import (
    custom_bad_request_view,
    custom_permission_denied_view,
    custom_page_not_found_view,
    custom_server_error_view,
)

urlpatterns = [

    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("home.urls")),
    path("products/", include("inventorize.urls")),
    path("products/", include("products.urls")),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('wishlist/', include('wishlist.urls')),
    #  allows to serve media files in development
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = custom_bad_request_view
handler403 = custom_permission_denied_view
handler404 = custom_page_not_found_view
handler500 = custom_server_error_view

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product, ProductSize
from profiles.models import UserProfile

from django.contrib.sites.models import Site


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="orders",
    )
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label="Country *", null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    day = models.CharField(default="1", null=False, blank=False)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0
    )
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0
    )
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0
    )
    original_bag = models.TextField(null=False, blank=False, default="")
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default=""
    )
    receipt_url = models.URLField(max_length=1024, null=True, blank=True)

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = (
            self.lineitems.aggregate(Sum("lineitem_total"))[
                "lineitem_total__sum"
            ]
            or 0
        )
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = (
                self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
            )
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def get_order_url(self):
        """
        Get the order url from the order_number
        """
        current_site = Site.objects.get_current()
        domain = current_site.domain
        return f"https://{domain}/profile/order_history/{self.order_number}"  # noqa: E501

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(
        Order,
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        related_name="lineitems",
    )
    product = models.ForeignKey(
        Product, null=False, blank=False, on_delete=models.CASCADE
    )
    product_size = models.ForeignKey(
        ProductSize,
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        related_name="lineitems",
    )
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, blank=False, editable=False
    )

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f"SKU {self.product.sku} on order {self.order.order_number}"

checkout/forms.py
from django import forms

from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = (
            'full_name',
            'email',
            'day',
            'phone_number',
            'street_address1',
            'street_address2',
            'town_or_city',
            'postcode',
            'country',
            'county',
        )

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove auto-generated labels
        and set autofocus on first field
        """
        super().__init__(*args, **kwargs)
        placeholders = {
            'full_name': 'Full Name',
            'email': 'Email Address',
            'day': 'Numbers of Days',
            'phone_number': 'Phone Number',
            'postcode': 'Postcode',
            'town_or_city': 'Town or City',
            'street_address1': 'Street Address 1',
            'street_address2': 'Street Address 2',
            'county': 'County, State or Locality',
        }

        # Set autofocus on first field
        self.fields['full_name'].widget.attrs['autofocus'] = True

        # Add placeholders and classes to form fields
        for field in self.fields:
            if field != 'country':
                if self.fields[field].required:
                    placeholder = f'{placeholders[field]} *'
                else:
                    placeholder = placeholders[field]
                self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].widget.attrs['class'] = 'stripe-style-input'
            self.fields[field].label = False

checkout/views.py
import stripe
import json

from django.db.models import F
from django.db import transaction
from django.shortcuts import (
    render,
    redirect,
    reverse,
    get_object_or_404,
    HttpResponse,
)
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.conf import settings
from django.contrib.auth import get_user_model

from profiles.forms import UserProfileForm
from profiles.models import UserProfile
from products.models import Product, ProductSize
from bag.contexts import bag_contents

from .forms import OrderForm
from .models import Order, OrderLineItem


@require_POST
def cache_checkout_data(request):

    # Verify that the bag hasn't changed between the time
    # the user started the checkout and when they submitted the form
    session_bag = request.session.get("bag", {})
    # make a copy of the bag in the session to compare with the updated bag
    session_bag_copy = session_bag.copy()
    # call the bag_contents function from contexts.py to update the bag
    current_bag = bag_contents(request)
    updated_bag = {
        item["product_size_id"]: item["quantity"]
        for item in current_bag["bag_items"]  # noqa
    }
    # Bag consistency check
    if session_bag_copy != updated_bag:
        messages.error(
            request,
            "The payment not processed because there was a change in your bag."
        )
        return HttpResponse(status=400, content="Bag changed")

    # Clean the bag with empty product sizes
    bag_for_metadata = []
    for item in current_bag["bag_items"]:
        if item["quantity"] > 0:
            bag_for_metadata.append(
                {
                    "product_id": item["product"].id,
                    "product_name": item["product"].name,
                    "product_size_id": item["product_size_id"],
                    "size": item["size"].name,
                    "quantity": item["quantity"],
                    "price": str(item["product"].price),
                    "color": item["product"].color.name,
                }
            )

    pid = request.POST.get("client_secret").split("_secret")[0]
    stripe.api_key = settings.STRIPE_SECRET_KEY
    try:
        stripe.PaymentIntent.modify(
            pid,
            metadata={
                "bag": json.dumps(bag_for_metadata),
                "save_info": request.POST.get("save_info"),
                "user": request.user,
                "order_total": current_bag["total"],
                "delivery_cost": current_bag["delivery"],
                "grand_total": current_bag["grand_total"],
            },
        )
        return HttpResponse(status=200)
    except Exception as e:
        messages.error(
            request,
            "Sorry, your payment cannot be \
            processed right now. Please try again later.",
        )
        return HttpResponse(content=e, status=400)


def checkout(request):
    stripe_public_key = settings.STRIPE_PUBLIC_KEY
    stripe_secret_key = settings.STRIPE_SECRET_KEY
    stripe.api_key = stripe_secret_key

    if request.method == "POST":
        # clean the bag with empty product sizes
        bag = {
            product_size_id: quantity
            for product_size_id, quantity in request.session["bag"].items()
            if quantity > 0
        }

        form_data = {
            "full_name": request.POST["full_name"],
            "email": request.POST["email"],
            "day": request.POST["day"],
            "phone_number": request.POST["phone_number"],
            "country": request.POST["country"],
            "postcode": request.POST["postcode"],
            "town_or_city": request.POST["town_or_city"],
            "street_address1": request.POST["street_address1"],
            "street_address2": request.POST["street_address2"],
            "county": request.POST["county"],
        }
        
        order_form = OrderForm(form_data)
        # transaction.atomic() ensures all database operations are
        # completed successfully
        if order_form.is_valid():
            order = order_form.save(commit=False)
            # get receipt_url from the stripe Charge object
            intent = stripe.PaymentIntent.retrieve(
                request.POST.get("client_secret").split("_secret")[0]
            )
            charge = stripe.Charge.retrieve(intent.latest_charge)
            metadata = charge.metadata
            receipt_url = charge.receipt_url

            pid = request.POST.get("client_secret").split("_secret")[0]
            order.stripe_pid = pid
            order.order_total = metadata.get("order_total", 0)
            order.delivery_cost = metadata.get("delivery_cost", 0)
            order.grand_total = metadata.get("grand_total", 0)
            order.receipt_url = receipt_url
            order.original_bag = metadata.get("bag", "")
            order.save()
            with transaction.atomic():
                # savepoint allows to rollback the transaction;
                # in this case, it is used to manually rollback the
                # transaction as the raised exception is handled
                savepoint = transaction.savepoint()
                for product_size_id, quantity in bag.items():
                    try:
                        # select_for_update allows to lock the selected
                        # product size to prevent race conditions until
                        # the transaction is complete
                        product_size_obj = ProductSize.objects.select_for_update().get(  # noqa
                            pk=product_size_id
                        )
                        order_line_item = OrderLineItem(
                            order=order,
                            product=product_size_obj.product,
                            product_size=product_size_obj,
                            quantity=quantity,
                        )
                        order_line_item.save()

                        # Decrease the product size quantity
                        product_size_obj.count = F("count") - quantity
                        product_size_obj.save()
                    except Product.DoesNotExist:
                        # rollback the transaction if there is an error
                        transaction.savepoint_rollback(savepoint)
                        order.delete()
                        messages.error(
                            request,
                            (
                                "One of the products in your bag wasn't"
                                " found in our database.\n"
                                "Please call us for assistance!"
                            ),
                        )
                        return redirect(reverse("view_bag"))

            request.session["save_info"] = bool(request.POST.get("save_info"))
            return redirect(
                reverse("checkout_success", args=[order.order_number])
            )
        else:
            messages.error(
                request,
                "There was an error with your form. \
                Please double check your information.",
            )
    else:
        # call the bag_contents function from contexts.py to update the bag
        # in the session
        current_bag = bag_contents(request)
        if not current_bag.get("bag_items") or current_bag["total"] == 0:
            messages.warning(
                request,
                "There's nothing in your cart at the moment.\n"
                "Return to shopping.",
            )
            return redirect(reverse("products"))

        total = current_bag["grand_total"]
        stripe_total = round(total * 100)
        stripe.api_key = stripe_secret_key
        intent = stripe.PaymentIntent.create(
            amount=stripe_total,
            currency=settings.STRIPE_CURRENCY,
        )

        if request.user.is_authenticated:
            try:
                profile = UserProfile.objects.get(user=request.user)
                order_form = OrderForm(
                    initial={
                        "full_name": profile.user.name,
                        "email": profile.user.email,
                        "phone_number": profile.default_phone_number,
                        "country": profile.default_country,
                        "postcode": profile.default_postcode,
                        "town_or_city": profile.default_town_or_city,
                        "street_address1": profile.default_street_address1,
                        "street_address2": profile.default_street_address2,
                        "county": profile.default_county,
                    }
                )
            except UserProfile.DoesNotExist:
                order_form = OrderForm()
        else:
            order_form = OrderForm()

    if not stripe_public_key:
        messages.warning(
            request,
            "Stripe public key is missing. \
            Did you forget to set it in your environment?",
        )

    template = "checkout/checkout.html"
    context = {
        "order_form": order_form,
        "stripe_public_key": stripe_public_key,
        "client_secret": intent.client_secret,
    }

    return render(request, template, context)


def checkout_success(request, order_number):
    """
    Handle successful checkouts
    """
    save_info = request.session.get("save_info")
    order = get_object_or_404(Order, order_number=order_number)

    if request.user.is_authenticated:
        # Attach the user's profile to the order
        profile = UserProfile.objects.get(user=request.user)
        order.user_profile = profile
        order.save()

        # Save the user's info
        if save_info:
            profile_data = {
                "name": order.full_name,
                "default_phone_number": order.phone_number,
                "default_country": order.country,
                "default_postcode": order.postcode,

checkout/templates/checkout/checkout.html
{% extends "base.html" %}
{% load static %}
{% load bag_tools %}

{% block extra_title %}- Checkout{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}

{% block content %}
<div class="container flex-grow-1 my-4">
  <div class="row">
    <div class="col">
      <h2 class="logo-font mb-4">Checkout</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-lg-6 order-lg-last mb-5">
      <p class="text-muted">Order Summary ({{ product_count }})</p>
      <div class="row">
        <div class="col-7 offset-2">
          <p class="mb-1 mt-0 small text-muted">Item</p>
        </div>
        <div class="col-3 text-right">
          <p class="mb-1 mt-0 small text-muted">Subtotal</p>
        </div>
      </div>
      {% for item in bag_items %}
        {% if item.quantity > 0 %}
          <div class="row">
            <div class="col-2 mb-1">
              <a href="{% url 'product_detail' item.product.id %}" aria-label="View {{ item.product.name }}">
                {% if item.product.image %}
                <img class="w-100" src="{{ item.product.image.url }}" alt="{{ product.name }}">
                {% else %}
                <img class="w-100" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                {% endif %}
              </a>
            </div>
            <div class="col-7">
              <p class="my-0"><strong>{{ item.product.name }}</strong></p>
              <p class="my-0 small">Size: {% if item.product.sizes %}{{ item.size.friendly_name }}{% else %}N/A{% endif %}</p>
              <p class="my-0 small">Color: {% if item.product.color %}{{ item.color.friendly_name }}{% else %}N/A{% endif %}</p>
              <p class="my-0 small text-muted">Qty: {{ item.quantity }}</p>
            </div>
            <div class="col-3 text-right">
              <p class="my-0 small text-muted">Rs. <span class="item-subtotal">{{ item.product.price | calc_subtotal:item.quantity }}</span></p>
            </div>
          </div>
        {% endif %}
      {% endfor %}
      <hr class="my-0">
      <div class="row text-black text-right">
        <div class="col-7 offset-2">
          <p class="my-0">Order Total:</p>
          <p class="my-0">Delivery:</p>
          <p class="my-0">Days Selected:</p>
          <p class="my-0">Grand Total:</p>
        </div>
        <div class="col-3">
          <p class="my-0">Rs. <span id="order-total">{{ total | floatformat:2 }}</span></p>
          <p class="my-0">Rs. <span id="delivery-cost">{{ delivery | floatformat:2 }}</span></p>
          <p class="my-0"><span id="days-selected">1</span> day(s)</p>
          <p class="my-0"><strong>Rs. <span id="grand-total">{{ grand_total | floatformat:2 }}</span></strong></p>
        </div>
      </div>
    </div>
    <div class="col-12 col-lg-6">
      <p class="text-muted">Please fill out the form below to complete your order</p>
      <form action="{% url 'checkout' %}" method="POST" id="payment-form">
        {% csrf_token %}
        <fieldset class="rounded px-3 mb-5">
          <legend class="fieldset-label small text-black px-2 w-auto">Details</legend>
          {{ order_form.full_name | as_crispy_field }}
          <div id="email--error" class="text-danger d-none">Please enter a valid email address.</div>
          {{ order_form.email | as_crispy_field }}
        </fieldset>


        <div class="px-3">
  <p>Days</p>
  <input 
    type="number" 
    name="{{ order_form.day.name }}" 
    id="{{ order_form.day.id_for_label }}" 
    class="form-control" 
    min="1" 
    value="{{ order_form.day.value|default_if_none:'1' }}" 
    required
    onchange="validateDayInput(this)"
  >
  {% if order_form.day.errors %}
    <div class="invalid-feedback">
      {{ order_form.day.errors }}
    </div>
  {% endif %}
</div>

        <fieldset class="rounded px-3 mb-5">
          <legend class="fieldset-label small text-black px-2 w-auto">Delivery</legend>
          <div id="phone--error" class="text-danger d-none">Phone can start with +, and must contain 7-15 digits with separators `<b>-</b>` or without them.</div>
          {{ order_form.phone_number | as_crispy_field }}
          {{ order_form.street_address1 | as_crispy_field }}
          {{ order_form.street_address2 | as_crispy_field }}
          {{ order_form.town_or_city | as_crispy_field }}
          {{ order_form.county | as_crispy_field }}
          {{ order_form.postcode | as_crispy_field }}
          {{ order_form.country | as_crispy_field }}
          <div class="form-check form-check-inline float-right mr-0">
            {% if user.is_authenticated %}
            <label class="form-check-label" for="id-save-info">Save this delivery information to my profile</label>
            <input class="form-check-input ml-2 mr-0" type="checkbox" id="id-save-info" name="save-info" checked>
            {% else %}
            <label class="form-check-label" for="id-save-info">
              <a class="text-info" href="{% url 'account_signup' %}">Create an account</a> or
              <a class="text-info" href="{% url 'account_login' %}">login</a> to save this information
            </label>
            {% endif %}
          </div>
        </fieldset>
        <fieldset class="px-3">
          <legend class="fieldset-label small text-black px-2 w-auto">Payment</legend>
          <!-- A Stripe card element will go here -->
          <div class="mb-3" id="card-element"></div>
          <!-- Used to display form errors -->
          <div class="mb-3 text-danger" id="card-errors" role="alert"></div>
          <!-- Pass the client secret to the view so we can get the payment intent id -->
          <input type="hidden" value="{{ client_secret }}" name="client_secret">
        </fieldset>

        <div class="submit-button text-right mt-5 mb-2">
          <a href="{% url 'view_bag' %}" class="btn btn-outline-info rounded-0">
            <span class="icon">
              <i class="fas fa-chevron-left"></i>
            </span>
            <span class="font-weight-bold">Adjust Bag</span>
          </a>
          <button id="submit-button" class="btn btn-success rounded-0">
            <span class="font-weight-bold">Complete Order</span>
            <span class="icon">
              <i class="fas fa-lock"></i>
            </span>
          </button>
          <p class="small text-danger my-0">
            <span class="icon">
              <i class="fas fa-exclamation-circle"></i>
            </span>
            <span>Your card will be charged <strong>Rs. <span id="final-amount">{{ grand_total|floatformat:2 }}</span></strong></span>
          </p>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Loading indicator -->
<div id="loading-overlay">
  <h1 class="text-light logo-font loading-spinner">
    <span class="icon">
      <i class="fas fa-3x fa-sync-alt fa-spin"></i>
    </span>
  </h1>
</div>
{% endblock %}

{% block postloadjs %}
  {{ block.super }}
  {{ stripe_public_key | json_script:"id_stripe_public_key" }}
  {{ client_secret | json_script:"id_client_secret" }}
  <script src="{% static 'checkout/js/stripe_elements.js' %}"></script>
  <script>
    // sr-only label for country select
    $('#div_id_country').prepend('<label class="sr-only" for="id_country">Select Country:</label>');
    
    // Update totals based on days selected
    $(document).ready(function() {
      // Initial values
      const initialOrderTotal = parseFloat($('#order-total').text());
      const initialDelivery = parseFloat($('#delivery-cost').text());
      
      // Function to update totals
      function updateTotals() {
        const days = parseInt($('#id_day').val());
        const newOrderTotal = initialOrderTotal * days;
        const newDelivery = initialDelivery * days;
        const newGrandTotal = newOrderTotal + newDelivery;
        
        // Update the displayed values
        $('#order-total').text(newOrderTotal.toFixed(2));
        $('#delivery-cost').text(newDelivery.toFixed(2));
        $('#days-selected').text(days);
        $('#grand-total').text(newGrandTotal.toFixed(2));
        $('#final-amount').text(newGrandTotal.toFixed(2));
      }
      
      // Update on page load
      updateTotals();
      
      // Update when days selection changes
      $('#id_day').change(updateTotals);
    });
function validateDayInput(input) {
  if (input.value < 1) {
    // alert("Days value must be at least 1");
    input.value = 1; // Reset to minimum valid value
    input.focus(); // Keep focus on the field for correction
  }
}

// Also validate on form submission
document.addEventListener('DOMContentLoaded', function() {
  const form = document.querySelector('form');
  if (form) {
    form.addEventListener('submit', function(e) {
      const dayInput = document.getElementById('{{ order_form.day.id_for_label }}');
      if (dayInput && dayInput.value < 1) {
        e.preventDefault(); // Stop form submission
        // alert("Days value must be at least 1");
        dayInput.value = 1;
        dayInput.focus();
      }
    });
  }
});

  </script>
{% endblock %}