bag/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.view_bag, name="view_bag"),
    path("add/<item_id>/", views.add_to_bag, name="add_to_bag"),
    path("adjust/<str:product_size_id>", views.adjust_bag, name="adjust_bag"),
    path(
        "remove/<str:product_size_id>",
        views.remove_from_bag,
        name="remove_from_bag",
    ),
]

cyclebay/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import (
    custom_bad_request_view,
    custom_permission_denied_view,
    custom_page_not_found_view,
    custom_server_error_view,
)

urlpatterns = [

    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("home.urls")),
    path("products/", include("inventorize.urls")),
    path("products/", include("products.urls")),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('wishlist/', include('wishlist.urls')),
    #  allows to serve media files in development
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = custom_bad_request_view
handler403 = custom_permission_denied_view
handler404 = custom_page_not_found_view
handler500 = custom_server_error_view

products/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.all_products, name="products"),
    path("featured/", views.featured_products, name="featured_products"),
    path("<int:product_id>/", views.product_detail, name="product_detail"),
]

products/models.py
from re import match
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError

from cyclebay.models import TimeStampModel


class Category(models.Model):
    name = models.CharField(max_length=254, unique=True)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    class Meta:
        verbose_name_plural = "categories"
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Brand(models.Model):
    name = models.CharField(max_length=254, unique=True)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Size(models.Model):
    name = models.CharField(max_length=50, unique=True)
    friendly_name = models.CharField(max_length=50, null=True, blank=True)
    order = models.PositiveIntegerField(unique=True)

    def __str__(self) -> str:
        return self.name

    def get_friendly_name(self):
        return self.friendly_name

    class Meta:
        ordering = ["order"]


def validate_color(value):
    """Validate the new color name if it is in hex format"""
    # match both shorthand HEX colors #RGB and full HEX colors #RRGGBB.
    regex = r"^#(?:[0-9a-fA-F]{3}){1,2}$"
    if not match(regex, value):
        raise ValidationError("Please enter a valid HEX color code!")


class Color(models.Model):
    # color name is the HEX color code
    name = models.CharField(
        max_length=7, unique=True, validators=[validate_color]
    )
    friendly_name = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(TimeStampModel):
    category = models.ForeignKey(
        "Category",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="products",
    )
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    brand = models.ForeignKey(
        Brand,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="products",
    )
    price = models.DecimalField(
        max_digits=7,
        decimal_places=2,
        validators=[MinValueValidator(0.01)],
        )
    sizes = models.ManyToManyField(
        Size,
        # specify the intermediate model that will be used
        # to link the two models together
        through="ProductSize",
        related_name="products",
    )
    color = models.ForeignKey(
        Color,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="products",
    )
    featured = models.BooleanField(default=False)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name

    def total_count(self):
        """Return the total count of all sizes of a product"""
        return ProductSize.objects.filter(product=self).aggregate(
            total=models.Sum("count")
        )["total"]


class ProductSize(models.Model):
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    count = models.IntegerField(
        default=0, validators=[MinValueValidator(0), MaxValueValidator(999)]
    )

    class Meta:
        # ensure that the combination of size and product is unique
        unique_together = ("size", "product")
        ordering = ["size"]

    def __str__(self) -> str:
        return f"{self.product.name} - {self.size.name}"

products/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.urls import reverse
from django.db.models import Q
from django.db.models.functions import Lower

from .utils import annotate_saved_products
from .models import Brand, Category, Color, Product


def all_products(request):
    """All products, including sorting and search queries"""
    products = Product.objects.all()
    query = None
    categories = None
    brands = None
    colors = None
    sort = None
    direction = None

    if request.GET:
        if "sort" in request.GET:
            # get the sort key from the request.GET
            sortkey = request.GET["sort"]
            sort = sortkey
            # annotate the products with the lower name if sorting by name
            if sortkey == "name":
                sortkey = "lower_name"
                products = products.annotate(lower_name=Lower("name"))
            # if sorting by category, brand or color use the name of the
            # category, brand or color instead of the id
            if sortkey == "category":
                sortkey = "category__name"
            if sortkey == "brand":
                sortkey = "brand__name"
            if sortkey == "color":
                sortkey = "color__name"
            # if direction is in the request.GET, get the direction
            if "direction" in request.GET:
                direction = request.GET["direction"]
                # if direction is desc, reverse the order of the sort key
                # for descending order, otherwise sort ascending
                if direction == "desc":
                    sortkey = f"-{sortkey}"
            products = products.order_by(sortkey)

        if "category" in request.GET:
            # get category string value and split it into a list
            categories = request.GET["category"].split(",")
            # exact case insensitive match for category name
            cat_query = Q()
            for category in categories:
                cat_query |= Q(name__iexact=category.strip())
            categories = Category.objects.filter(cat_query)
            # filter products by category
            products = products.filter(category__in=categories)

        if "brand" in request.GET:
            brands = request.GET["brand"].split(",")
            br_query = Q()
            for brand in brands:
                br_query |= Q(name__iexact=brand.strip())
            brands = Brand.objects.filter(br_query)
            products = products.filter(brand__in=brands)

        if "color" in request.GET:
            colors = request.GET["color"].split(",")
            col_query = Q()
            for color in colors:
                col_query |= Q(name__iexact=color.strip())
            colors = Color.objects.filter(col_query)
            products = products.filter(color__in=colors)

        if "q" in request.GET:
            # get the search query
            query = request.GET["q"]
            if not query.strip():
                messages.error(
                    request, "You didn't enter any search criteria!"
                )
                return redirect(reverse("products"))
            # look for the query in the product name or brand name
            queries = (
                Q(name__icontains=query)
                | Q(brand__name__icontains=query)
            )
            products = products.filter(queries)

    current_sorting = f"{sort}_{direction}"

    if request.user.is_authenticated:
        products = annotate_saved_products(products, request.user)

    context = {
        "products": products,
        "search_term": query,
        "current_categories": categories,
        "current_brands": brands,
        "current_colors": colors,
        "current_sorting": current_sorting,
    }
    return render(request, "products/products.html", context)


def featured_products(request):
    """Featured products"""
    products = Product.objects.filter(featured=True)
    if request.user.is_authenticated:
        products = annotate_saved_products(products, request.user)
    context = {
        "products": products,
    }
    return render(request, "products/products.html", context)


def product_detail(request, product_id):
    """Individual product details"""
    product = get_object_or_404(Product, pk=product_id)
    context = {
        "product": product,
    }
    return render(request, "products/product_detail.html", context)

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}

{% block extra_title %}- {{ product.name }}{% endblock %}

{% block content %}
<div class="container-fluid py-2 flex-grow-1">
  <div class="row d-flex justify-content-center">
    <div class="col-12 col-md-6 col-lg-5 col-xl-4">
      <div class="image-container my-5">
        {% if product.image %}
        <a href="{{ product.image.url }}" target="_blank">
          <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
        </a>
        {% else %}
        <a href="">
          <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
        </a>
        {% endif %}
      </div>
    </div>
    <div class="col-12 col-md-6 col-lg-5 col-xl-4">
      <div class="product-details-container mb-5 mt-md-5 mx-sm-2 mx">
        <div class="product-details-header">
          <p class="mb-0">{{ product.name }}</p>
          <p class="lead mb-0 text-left font-weight-bold">&euro;{{ product.price }}</p>
        </div>

       <ul class="list-unstyled mt-2 mt-md-3">
          {% if product.brand %}
            <li class="small mt-1 mb-0">
              <a class="text-muted" href="{% url 'products' %}?brand={{ product.brand.name|urlencode }}">
                <i class="fas fa-trademark mr-1"></i>{{ product.brand.friendly_name }}
              </a>
            </li>
          {% endif %}
          {% if product.category %}
            <li class="small mt-1 mb-0">
              <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name|urlencode }}">
                <i class="fas fa-folder-open mr-1"></i>{{ product.category.friendly_name }}
              </a>
            </li>
          {% endif %}
          {% if product.color %}
            <li class="small mt-1 mb-0">
              <a class="text-muted" href="{% url 'products' %}?color={{ product.color.name|urlencode  }}">
                <i class="fas fa-palette mr-1"></i>{{ product.color.friendly_name }}
              </a>
            </li>
          {% endif %}
       </ul>

      <!-- Superusers control buttons -->
      {% if request.user.is_superuser %}
        <small class="ml-3">
          <a href="{% url 'edit_product' product.id %}">Edit</a> |
          <a href="{% url 'delete_product' product.id %}" class="remove-item text-danger" role="button">
            Delete
          </a>
        </small>
      {% endif %}

        <form id="add-to-bag-form" class="form" action="{% url 'add_to_bag' product.id %}" method="POST" novalidate>
          {% csrf_token %}
          <div class="form-row">
            <div class="col-12">
              {% if product.total_count %}
                <div class="sizes mt-2 mt-md-4">
                  <h6 class="text-uppercase"><strong>Size</strong></h6>
                  <div class="sizes-container ml-1">
                    {% for productsize in product.productsize_set.all %}
                    <label class="radio" data-toogle="tooltip" data-placement="top"
                    {% if not productsize.count %}title="Out of stock" {% else %} title="{{ productsize.count }} in stock" {% endif %}>
                      <input type="radio" name="productsize" value="{{ productsize.size.name }}"
                        {% if not productsize.count %} disabled {% endif %} required>
                      <span>{{ productsize.size.name }}</span>
                    </label>
                    {% endfor %}
                  </div>
                  <!-- Alert if radio button not checked -->
                  <div class="d-none alert alert-danger fade w-100" role="alert">
                    Please select a size
                    <button type="button" class="close ml-2" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                </div>
              {% else %}
                <p class="text-danger mt-2"><strong>Out of stock</strong></p>
                <!-- hidden input -->
                <input type="hidden" name="is_out_of_stock" value="true">
              {% endif %}
            </div>

            <div class="col d-flex justify-content-around justify-content-sm-start mt-3 ml-sm-1 ml-md-0">
              <a href="{% url 'products' %}" class="btn btn-outline-secondary mr-2">
                <span class="icon">
                  <i class="fas fa-chevron-left"></i>
                </span>
                <span class="text-uppercase">Keep Shopping</span>
              </a>
              <button type="submit" class="btn btn-info text-uppercase">
                <span class="icon">
                  <i class="fas fa-cart-plus"></i>
                </span>
                <span>Add to Cart</span>
              </button>
            </div>
            <input type="hidden" name="redirect_url" value="{{ request.path }}">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- modal for superusers to delete product -->
{% include 'includes/modals/error_modal.html' %}

{% endblock %}

{% block postloadjs %}
  {{ block.super }}
  <script>
    $(document).ready(function(){
      $('.sizes label').tooltip();
    });
  </script>
  <script>
    // Alert if radio button not checked
    $('#add-to-bag-form').submit(function(e) {
      if (!$("form input[type='radio']").is(':checked')) {
        e.preventDefault();
        $('.alert').addClass('d-block show');
        $('.sizes h6').addClass('text-danger');
        $('.sizes-container').addClass('horizontal-shake');
      }
    });
    // Remove alert if radio button checked
    $("form input[type='radio']").change(function() {
      $('.alert').removeClass('d-block show');
      $('.sizes h6').removeClass('text-danger');
      $('.sizes-container').removeClass('horizontal-shake');
    });
  </script>
  <script>
    const isOutOfStock = $('input[name="is_out_of_stock"]');
    if (isOutOfStock.val()) {
      $('#add-to-bag-form button[type="submit"]').prop('disabled', true);
    };
  </script>
{% if request.user.is_superuser %}
<!-- Delete product script that use the error modal for superusers  -->
<script>
  // Remove item and reload on click
  $(document).ready(function () {
    // modal trigger
    const csrfToken = "{{ csrf_token }}";
    const productsUrl = "{% url 'products' %}";
    const homeUrl = "{% url 'home' %}";
    const modalTrigger = $(".remove-item");
    const errorModal = $('#errorModal');
    const submitBtn = errorModal.find(".submit");

    // get data from clicked modal trigger and set it to submit button on modal
    modalTrigger.click(function (e) {
      e.preventDefault();
      const url = $(this).attr('href');

      submitBtn.attr('data-url', url);
      errorModal.modal('show');
    });

    // Get passed url from submit button and post it to remove_item view
    submitBtn.on('click', function () {
      const url = $(this).attr('data-url');
      $.post(url, { 'csrfmiddlewaretoken': csrfToken })
        .done(function () {
          location.href = productsUrl;
        })
        .fail(function (xhr, status, error) {
          location.href = homeUrl;
        });
    });

  });
</script>
{% endif %}
{% endblock %}

products/templates/products/products.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}- Products{% endblock %}

{% block extra_css %}
<style>
  .lazy-load {
    background: url('{{ MEDIA_URL }}loading.gif') no-repeat center;
    background-size: auto;
    min-height: 15rem;
    opacity: 0.6;
    transition: opacity 1s ease-in-out;
  }
</style>

{% endblock %}

{% block content %}
<section class="bg-light py-4 flex-grow-1">
  <div class="container">
    <header>
      <div class="row mb-2">
        <div class="col text-center">
          <h2 class="logo-font">Bikes</h2>
        </div>
      </div>
      <!-- Show current brand, category or color -->
      <div class="row">
        <div class="col">
          <ul class="list-inline mb-0">
            {% if current_categories %}
              <li>
                <ul class="list-inline">
                  <h3 class="display-6 d-inline-block mb-0">
                    <i class="fas fa-tags mr-1"></i>
                    Categor{{ current_categories|length|pluralize:"y,ies" }}:
                  </h3>
                  {% for c in current_categories %}
                    <li class="list-inline-item mr-0">
                      <a href="{% url 'products' %}?category={{ c.name|urlencode }}">
                        {{ c.friendly_name }}
                      </a>
                    {% if not forloop.last %},{% endif %}
                    </li>
                  {% endfor %}
                </ul>
              </li>
            {% endif %}
            {% if current_brands %}
              <li>
                <ul class="list-inline">
                  <h3 class="display-6 d-inline-block mb-0">
                    <i class="fas fa-registered mr-1"></i>
                    Brand{{ current_brands|length|pluralize:"s" }}:
                  </h3>
                  {% for b in current_brands %}
                    <li class="list-inline-item mr-0">
                      <a href="{% url 'products' %}?brand={{ b.name|urlencode }}">
                        {{ b.friendly_name }}
                      </a>
                    {% if not forloop.last %},{% endif %}
                    </li>
                  {% endfor %}
                </ul>
              </li>
            {% endif %}
            {% if current_colors %}
              <li>
                <ul class="list-inline">
                  <h3 class="display-6 d-inline-block mb-0">
                    <i class="fas fa-palette mr-1"></i>
                    Color{{ current_colors|length|pluralize:"s" }}:
                  </h3>
                  {% for col in current_colors %}
                  <li class="list-inline-item mr-0">
                    <a href="{% url 'products' %}?color={{ col.name|urlencode }}">
                      {{ col.friendly_name }}
                    </a>
                    {% if not forloop.last %},{% endif %}
                  </li>
                  {% endfor %}
                </ul>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
      <!-- ./current brand, category or color -->

      <!-- Products count and sort selector -->
      <div class="row my-3">
        <div class="col-6 my-auto">
          <p class="text-muted-black mb-0">
            {{ products|length }} Products{% if search_term %} found for <strong>"{{ search_term }}"</strong>{% endif %}
          </p>
        </div>
        <div class="col-6 my-auto d-flex justify-content-end">
          <div class="sort-select-wrapper">
            <label for="sort-selector" class="sr-only">Sort by:</label>
            <select id="sort-selector"
              class="custom-select custom-select-sm rounded-0 border border-{% if current_sorting != 'None_None' %}info{% else %}black{% endif %}">
              <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort by...</option>
              <option value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>Price (low to high)
              </option>
              <option value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>Price (high to low)
              </option>
              <option value="name_asc" {% if current_sorting == 'name_asc' %}selected{% endif %}>Name (A-Z)</option>
              <option value="name_desc" {% if current_sorting == 'name_desc' %}selected{% endif %}>Name (Z-A)</option>
              <option value="category_asc" {% if current_sorting == 'category_asc' %}selected{% endif %}>Category (A-Z)
              </option>
              <option value="category_desc" {% if current_sorting == 'category_desc' %}selected{% endif %}>Category (Z-A)
              </option>
              <option value="brand_asc" {% if current_sorting == 'brand_asc' %}selected{% endif %}>Brand (A-Z)
              </option>
              <option value="brand_desc" {% if current_sorting == 'brand_desc' %}selected{% endif %}>Brand (Z-A)
              </option>
              <option value="color_asc" {% if current_sorting == 'color_asc' %}selected{% endif %}>Color (A-Z)
              </option>
              <option value="color_desc" {% if current_sorting == 'color_desc' %}selected{% endif %}>Color (Z-A)
              </option>
            </select>
          </div>
        </div>
      </div>
      <!-- ./products count and sort selector -->
    </header>

    <!-- Products -->
    <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 row-cols-xl-4">
      {% for product in products %}
      <div class="col px-2 mb-2 mb-sm-3">
        <div class="card h-100 product-list-card">
          <div class="card-header bg-white border-bottom-0 d-flex justify-content-between">
            <!-- brand -->
            <div>
              {% if product.brand %}
                <a class="badge badge-pill badge-light brand-badge text-muted-black"
                  href="{% url 'products' %}?brand={{ product.brand.name|urlencode }}">
                  <i class="fas fa-registered mr-1"></i>
                  {{ product.brand.friendly_name }}
                </a>
              {% endif %}
            </div>
            <!-- color badges -->
            <ul class="list-inline mb-0 text-center color-list"
              data-color="{{ product.color.name }}"
              data-colorFriendlyName="{{ product.color.friendly_name }}">
            </ul>
          </div>
          <!-- product image -->
          <div class="position-relative text-center">
            {% if product.featured %}
            <!-- attach badge if product is featured -->
              <span class="ribbon-featured">Hot</span>
            {% endif %}
            {% if product.image %}
            <a href="{% url 'product_detail' product.id %}">
              <img class="card-img-top lazy-load" data-src="{{ product.image.url }}" alt="{{ product.name }}">
            </a>
            {% else %}
            <a href="{% url 'product_detail' product.id %}">
              <img class="card-img-top lazy-load" data-src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
            </a>
            {% endif %}
          </div>
          <!-- product name -->
          <div class="card-body py-2">
            <h4 class="display-6 card-title mb-0">{{ product.name }}</h4>
            <p class="card-text mb-0 font-weight-bold">
              &euro;{{ product.price }}
            </p>
            {% if product.category %}
            <p class="card-text small mt-1 mb-0">
              <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name|urlencode }}">
                <small><i class="fas fa-tags mr-1"></i>{{ product.category.friendly_name }}</small>
              </a>
            </p>
            {% endif %}
          </div>
          <div class="card-footer py-2 px-4 border-0 bg-transparent d-flex justify-content-between align-items-center">
            {% if not product.total_count %}
              <span class="text-danger">Out of stock</span>
            {% else %}
              <a href="{% url 'product_detail' product.id %}" class="btn btn-sm btn-outline-info py-0"
                aria-label="View product details" role="button">
                <i class="fas fa-eye"></i>
              </a>
            {% endif %}
            {% if request.user.is_authenticated %}
              {% if request.user.is_superuser %}
                <!-- if superuser display superusers control buttons -->
                <small class="ml-3">
                  <a href="{% url 'edit_product' product.id %}">Edit</a> |
                  <a href="{% url 'delete_product' product.id %}" class="remove-item text-danger" role="button">
                    Delete
                  </a>
                </small>
              {% endif %}
              <button class="wishlist-toggler p-0 m-0 btn-save{% if product.is_in_wishlist %}-active{% endif %}"
                type="button" aria-label="Add to wishlist toggler" data-url="{% url 'add_to_wishlist_toggle' product.id %}">
              </button>
            {% else %}
              <!-- if user not authenticated redirect to login page -->
              <a href="{% url 'account_login' %}?next={{ request.path }}" class="btn-save"
                aria-label="Add to wishlist button"></a>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <!-- ./products -->

  </div>
</section>

<!-- back to top button -->
<div class="btt-button bg-white shadow-sm rounded-0 border border-black">
  <a class="btt-link d-flex h-100" href="#" aria-label="Back to top">
    <i class="fas fa-arrow-up text-black mx-auto my-auto"></i>
  </a>
</div>

<!-- modal for superusers to delete product -->
{% include 'includes/modals/error_modal.html' %}


{% endblock %}

{% block postloadjs %}
{{ block.super }}
<!-- pass csrf token -->
<script>
  var csrfToken = '{{ csrf_token }}';
</script>
<script src="{% static 'wishlist/js/wishlist_toggler.js' %}"></script>

<script>
  $('.btt-link').click(function (e) {
    window.scrollTo(0, 0)
  })
</script>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    // Attach color badges to each product
    const colorLists = document.querySelectorAll('.color-list');

    colorLists.forEach(list => {
      const color = list.dataset.color;
      const friendlyName = list.dataset.colorfriendlyname;

      // if color is a valid hex code or whole word color
      // add a list item color badge with a background color of that color
      if (color.startsWith('#') || /^[a-zA-Z]+$/.test(color)) {
        const li = document.createElement('li');
        // replace # with %23 to pass hex color in url
        const parsedColor = color.startsWith('#') ? color.replace("#", "%23") : color;
        li.classList.add("list-inline-item","color-badge", "position-relative");
        li.style.backgroundColor = color;
        // add a stretched-link to filter by that color
        li.innerHTML = `<a class="stretched-link" href="{% url 'products' %}?color=${parsedColor}" aria-label="Filter by ${friendlyName}"></a>`;

        // Add tooltip to color badge
        li.setAttribute('data-toggle', 'tooltip');
        li.setAttribute('data-placement', 'top');
        li.setAttribute('title', friendlyName);
        // initialize tooltip
        li.addEventListener('mouseover', function() {
          $(this).tooltip('show');
        });
        list.appendChild(li);
      }
    });
  });
</script>

<script>
  $('#sort-selector').change(function () {
    var selector = $(this);
    var currentUrl = new URL(window.location);

    var selectedVal = selector.val();
    if (selectedVal != "reset") {
      var sort = selectedVal.split("_")[0];
      var direction = selectedVal.split("_")[1];

      currentUrl.searchParams.set("sort", sort);
      currentUrl.searchParams.set("direction", direction);

      window.location.replace(currentUrl);
    } else {
      currentUrl.searchParams.delete("sort");
      currentUrl.searchParams.delete("direction");

      window.location.replace(currentUrl);
    }
  })
</script>
<!-- Delete product script that use the error modal for superusers  -->
<script>
  // Remove item and reload on click
  $(document).ready(function () {
    // modal trigger
    const csrfToken = "{{ csrf_token }}";
    const productsUrl = "{% url 'products' %}";
    const homeUrl = "{% url 'home' %}";
    const modalTrigger = $(".remove-item");
    const errorModal = $('#errorModal');
    const submitBtn = errorModal.find(".submit");

    // get data from clicked modal trigger and set it to submit button on modal
    modalTrigger.click(function (e) {
      e.preventDefault();
      const url = $(this).attr('href');

      submitBtn.attr('data-url', url);
      errorModal.modal('show');
    });

    // Get passed url from submit button and post it to remove_item view
    submitBtn.on('click', function () {
      const url = $(this).attr('data-url');
      $.post(url, { 'csrfmiddlewaretoken': csrfToken })
        .done(function () {
          location.href = productsUrl;
        })
        .fail(function (xhr, status, error) {
          location.href = homeUrl;
        });
    });
  });
</script>
<script>
  // Lazy load images using Intersection Observer
  $(document).ready(function() {
    // Initialize Intersection Observer
    const observer = new IntersectionObserver((entries, observer) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          let el = $(entry.target);
          el.attr('src', el.data('src'));
          el.removeClass('lazy-load'); // remove the class to avoid re-loading
          observer.unobserve(entry.target); // Stop observing this element
        }
      });
    }, {
      // Load images 100px before they appear on viewport.
      rootMargin: '100px'
    });

    // Observe each element with the 'lazy-load' class
    $('.lazy-load').each(function() {
      observer.observe(this);
    });
  });
</script>
{% endblock %}